name        : gnome-backgrounds
version     : 3.18.0
release     : 6
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnome-backgrounds/3.18/gnome-backgrounds-3.18.0.tar.xz : aa560f0e5f12a308dd36aaac2fff32916abd61d42f47b4bc42c8c7011bf2a7b9
license     :
    - GPL-2.0
summary     : Default GNOME artwork
description : |
    Default GNOME artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
