name       : gnome-backgrounds
version    : 3.28.0
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/3.28/gnome-backgrounds-3.28.0.tar.xz : b25b963d9d1ce076b489ef1e85c6540166f2312c77132f4ec0ecc90f3da8f1e1
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
