name       : gnome-backgrounds
version    : '44.0'
release    : 17
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/44/gnome-backgrounds-44.0.tar.xz : 4a8393b387135f2a6a424a1a0c3ac94e0742b62b8235a0923c929f51e04be04e
homepage   : https://gitlab.gnome.org/GNOME/gnome-backgrounds
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -m00644 $pkgfiles/*.jpg -t $installdir/usr/share/backgrounds/gnome/
