name       : gnome-backgrounds
version    : 3.38.0
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/3.38/gnome-backgrounds-3.38.0.tar.xz : f7712a873a80c9a9fcf3952611effeb2d9aed23a3e8abfcda8afb15c427d1ee3
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -m00644 $pkgfiles/*.jpg -t $installdir/usr/share/backgrounds/gnome/
