name       : gnome-backgrounds
version    : 3.26.2
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/3.26/gnome-backgrounds-3.26.2.tar.xz : 3a8ba8d3463d70bce2377b168218e32367c0020f2d0caf611e7e39066081f94f
license    : GPL-2.0
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
