name       : gnome-backgrounds
version    : 3.32.0
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/3.32/gnome-backgrounds-3.32.0.tar.xz : 3f53c31bc9ff31b27408159afe77d06875174bc554e4e7c225a4d5d16acbb3e8
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
