name       : gnome-backgrounds
version    : '41.0'
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/41/gnome-backgrounds-41.0.tar.xz : 1da1ac0d261bedf0fcd2c85b480bc65505e23cf51f1143126c0d37717e693145
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -m00644 $pkgfiles/*.jpg -t $installdir/usr/share/backgrounds/gnome/
