name       : gnome-backgrounds
version    : 3.24.0
release    : 9
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/gnome-backgrounds/3.24/gnome-backgrounds-3.24.0.tar.xz : cbda4c2159292940fa4b972df77379be716590c7b62bb4b2b9fa8e99749c71ca
license    : GPL-2.0
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
