name       : gnome-backgrounds
version    : '3.20'
release    : 7
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnome-backgrounds/3.20/gnome-backgrounds-3.20.tar.xz : d66c6e165e5c16b79ee4ab83102fa73fa20ce4e14191036ee68e8e82cf537127
license    :
    - GPL-2.0
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
