name       : gnome-backgrounds
version    : '42.0'
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/42/gnome-backgrounds-42.0.tar.xz : 4c7fe1a09f459c5f77189a5982524fce05d888944955d679910f234606c1295d
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -m00644 $pkgfiles/*.jpg -t $installdir/usr/share/backgrounds/gnome/
