name       : gnome-backgrounds
version    : 3.22.1
release    : 8
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnome-backgrounds/3.22/gnome-backgrounds-3.22.1.tar.xz : bfc89812b26383b74062c43f6c175b8fce19d4044b42f8bc9de2ab196a6eee25
license    : GPL-2.0
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
